version: "2.4"
services:
  grafana:
    image: "grafana/grafana:8.4.3"
    container_name: "grafana"
    restart: "always"
    user: "${HOST_USER}"
    volumes:
      - "${DATA_HOME}/data/grafana:/var/lib/grafana"
    logging:
      driver: "journald"
    mem_limit: 256m
    memswap_limit: 0m
    ports:
      - "0.0.0.0:3000:3000"
  prometheus:
    image: "prom/prometheus:v2.25.0"
    container_name: "prometheus"
    restart: "always"
    user: "${HOST_USER}"
    volumes:
      - "${DATA_HOME}/data/prometheus:/prometheus"
      - "${DATA_HOME}/config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
    logging:
      driver: "journald"
    mem_limit: 256m
    memswap_limit: 0m
    ports:
      - "127.0.0.1:9090:9090"
  kotbot:
    image: "ghcr.io/heapy/kotbot:${KOTBOT_VERSION}"
    container_name: "kotbot"
    restart: "always"
    user: "${HOST_USER}"
    environment:
      KOTBOT_OPTS: "-Xmx128m"
      KOTBOT_TOKEN: "${KOTBOT_TOKEN}"
      KOTBOT_VERSION: "${KOTBOT_VERSION}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "journald"
    mem_limit: 256m
    memswap_limit: 0
  mtproto:
    container_name: "mtproto"
    image: "heapy/mtproto:latest"
    restart: "always"
    environment:
      PROXY_SECRET: "${PROXY_SECRET}"
    logging:
      driver: "journald"
    mem_limit: 256m
    memswap_limit: 0m
    ports:
      - "0.0.0.0:8888:8888"
  heapy_kotlin_jobs:
    container_name: "heapy_kotlin_jobs"
    image: "ghcr.io/heapy/kotlin_jobs:main"
    restart: "always"
    logging:
      driver: "journald"
    mem_limit: 16m
    memswap_limit: 0m
    ports:
      - "127.0.0.1:8098:80"
  heapy_io:
    container_name: "heapy_io"
    image: "ghcr.io/heapy/heapy.io:main"
    restart: "always"
    logging:
      driver: "journald"
    mem_limit: 16m
    memswap_limit: 0m
    ports:
      - "127.0.0.1:8099:80"
  wireguard:
    container_name: "wireguard"
    image: "weejewel/wg-easy"
    restart: "always"
    environment:
      WG_HOST: "heapy.io"
      PASSWORD: "${WIREGUARD_PASSWORD}"
    volumes:
      - "${DATA_HOME}/data/wireguard:/etc/wireguard"
    logging:
      driver: "journald"
    mem_limit: 1024m
    memswap_limit: 0m
    ports:
      - "51820:51820/udp"
      - "127.0.0.1:51821:51821/tcp"
    cap_add:
      - "NET_ADMIN"
      - "SYS_MODULE"
    sysctls:
      - "net.ipv4.conf.all.src_valid_mark=1"
      - "net.ipv4.ip_forward=1"
