version: "2.4"
services:
  prometheus:
    image: "prom/prometheus:v2.25.0"
    container_name: "prometheus"
    restart: "always"
    user: "${HOST_USER}"
    volumes:
      - "${DATA_HOME}/data/prometheus:/prometheus"
      - "${DATA_HOME}/config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
    logging:
      driver: "journald"
    mem_limit: 256m
    memswap_limit: 0m
    ports:
      - "127.0.0.1:9090:9090"
  kotbot:
    image: "heapy/kotbot:${KOTBOT_RELEASE}"
    container_name: "kotbot"
    restart: "always"
    user: "${HOST_USER}"
    environment:
      KOTBOT_OPTS: "-Xmx128m"
      KOTBOT_TOKEN: "${KOTBOT_TOKEN}"
      KOTBOT_RELEASE: "${KOTBOT_RELEASE}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "journald"
    mem_limit: 256m
    memswap_limit: 0
  tgto:
    image: "ghcr.io/heapy/tgto:${TGTO_RELEASE}"
    container_name: "tgto"
    restart: "always"
    environment:
      TGTO_OPTS: "-Xmx64m"
      TGTO_BOT_TOKEN: "${TGTO_BOT_TOKEN}"
      TGTO_BASE_URL: "${TGTO_BASE_URL}"
      TGTO_STORE_PATH: "${TGTO_STORE_PATH}"
    volumes:
      - "${DATA_HOME}/data/tgto/xodus:/data/xodus"
    logging:
      driver: "journald"
    mem_limit: 256m
    memswap_limit: 0m
    ports:
      - "127.0.0.1:8090:8080"
  repo_kotlin_link:
    image: "ghcr.io/heapy/repo.kotlin.link:${REPO_KOTLIN_LINK_RELEASE}"
    container_name: "repo.kotlin.link"
    restart: "always"
    logging:
      driver: "journald"
    mem_limit: 256m
    memswap_limit: 0m
    ports:
      - "127.0.0.1:8092:8080"
  ttrss_database:
    container_name: "ttrss_database"
    image: "postgres:10.16"
    restart: "always"
    user: "${HOST_USER}"
    environment:
      POSTGRES_USER: "tinytinyrss"
      POSTGRES_PASSWORD: "HPALUhAY28G4LWDf"
      POSTGRES_DB: "tinytinyrss"
    volumes:
      - "${DATA_HOME}/data/ttrss/pgdata:/var/lib/postgresql/data"
      - "/etc/passwd:/etc/passwd:ro"
    logging:
      driver: "journald"
    mem_limit: 512m
    memswap_limit: 0m
  ttrss:
    container_name: "ttrss"
    image: "heapy/ttrss:${TTRSS_RELEASE}"
    restart: "always"
    volumes:
      - "${DATA_HOME}/data/ttrss/data/cache:/ttrss/reader/cache"
      - "${DATA_HOME}/data/ttrss/data/lock:/ttrss/reader/lock"
      - "${DATA_HOME}/data/ttrss/data/feed-icons:/ttrss/reader/feed-icons"
    logging:
      driver: "journald"
    mem_limit: 256m
    memswap_limit: 0m
    depends_on:
      - ttrss_database
  ttrss_nginx:
    container_name: "ttrss_nginx"
    image: "heapy/ttrss-nginx:latest"
    command: ["nginx-debug", "-g", "daemon off;"]
    restart: "always"
    volumes:
      - "${DATA_HOME}/data/ttrss/data/cache:/ttrss/reader/cache"
      - "${DATA_HOME}/data/ttrss/data/lock:/ttrss/reader/lock"
      - "${DATA_HOME}/data/ttrss/data/feed-icons:/ttrss/reader/feed-icons"
    ports:
      - "127.0.0.1:8093:80"
    logging:
      driver: "journald"
    mem_limit: 64m
    memswap_limit: 0m
    depends_on:
      - ttrss
  mtproto:
    container_name: "mtproto"
    image: "heapy/mtproto:latest"
    restart: "always"
    environment:
      PROXY_SECRET: "${PROXY_SECRET}"
    logging:
      driver: "journald"
    mem_limit: 256m
    memswap_limit: 0m
    ports:
      - "0.0.0.0:8888:8888"
