# https://github.com/grafana/loki/blob/main/clients/cmd/promtail/promtail-docker-config.yaml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://monitoring_loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: journal
    journal:
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: [ "__journal__systemd_unit" ]
        target_label: "systemd_unit"
