server {
  listen 80;
  server_name ibragimov.by;
  root /ttrss;

  location ~ \.php$ {
    fastcgi_pass ttrss:9000;
    fastcgi_index index.php;
    include fastcgi_params;
  }

  location / {
    try_files $uri $uri/ =404;
  }
}
