#!/bin/bash

# Install script
# source /home/pi/heapy-configuration/birdperson/functions

PROJECT="/home/pi/heapy-configuration/birdperson";

function hh_system_update() {
  echo "[📦] Update packages"
  sudo apt update
  sudo apt list --upgradable
  sudo apt dist-upgrade -y
  sudo apt autoremove -y
  sudo apt autoclean
  sudo apt clean
}

function hh_cloudflare_update() {
    sudo cloudflared version
    sudo cloudflared update
    sudo cloudflared version
}

function hh_pull_docker_images() {
  echo "[🆕] Pull latest images"
  docker pull eclipse-mosquitto:2.0
  docker pull koenkk/zigbee2mqtt:1.37.1
  docker pull ghcr.io/home-assistant/home-assistant:2024.5
  docker pull prom/prometheus:v2.51.2
}

function hh_compose_up() {
  echo "[🌈] Update containers"
  cd "${PROJECT}" || exit 1
  docker compose up -d
}

function hh_prune_docker_images() {
  echo "[🧹] Remove unused images";
  docker system prune -f;
}

function hh_update() {
  hh_system_update;
  hh_pull_docker_images;
  hh_compose_up;
  hh_prune_docker_images;
}

function home() {
  cd $PROJECT || exit 1
}

alias temp="/usr/bin/vcgencmd measure_temp";

alias ll='ls -alhF'

case "$1" in
  hh_update_docker)
    hh_pull_docker_images;
    hh_compose_up;
    ;;
  *)
    ;;
esac
