networks:
  schwifty:
    name: schwifty
    driver: bridge

services:
  cloudflared:
    container_name: "cloudflared"
    image: "cloudflare/cloudflared:latest"
    command: [ "tunnel", "--no-autoupdate", "run"]
    restart: always
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    logging:
      driver: "journald"
    networks:
      - schwifty
    depends_on:
      - heapy_io
      - ruslan_ibragimov_by
      - ibragimov_by

  ruslan_ibragimov_by:
    container_name: "ruslan.ibragimov.by"
    image: "ghcr.io/irus/blog:main"
    restart: "always"
    logging:
      driver: "journald"
    stop_grace_period: 30s
    networks:
      - schwifty

  heapy_io:
    image: "nginx:stable-alpine"
    container_name: "heapy.io-ingress"
    restart: "always"
    logging:
      driver: "journald"
    volumes:
      - ./heapy_io/nginx/conf.d:/etc/nginx/conf.d
    stop_grace_period: 30s
    networks:
      - schwifty
    depends_on:
      - heapy_io_kotlin_jobs
      - heapy_io_root

  heapy_io_kotlin_jobs:
    container_name: "heapy.io-kotlin_jobs"
    image: "ghcr.io/heapy/kotlin_jobs:main"
    restart: "always"
    logging:
      driver: "journald"
    stop_grace_period: 30s
    networks:
      - schwifty

  heapy_io_root:
    container_name: "heapy.io"
    image: "ghcr.io/heapy/heapy.io:main"
    restart: "always"
    logging:
      driver: "journald"
    stop_grace_period: 30s
    networks:
      - schwifty

  ibragimov_by:
    image: "nginx:stable-alpine"
    container_name: "ibragimov.by-ingress"
    restart: "always"
    logging:
      driver: "journald"
    volumes:
      - ./ibragimov_by/nginx/conf.d:/etc/nginx/conf.d
    stop_grace_period: 30s
    networks:
      - schwifty
    depends_on:
      - ttrss_nginx
      - ibragimov_by_currency

  ibragimov_by_currency:
    container_name: "ibragimov.by-currency"
    image: "ghcr.io/irus/currency:main"
    restart: "always"
    logging:
      driver: "journald"
    stop_grace_period: 30s
    networks:
      - schwifty

  ttrss_database:
    container_name: "ttrss_database"
    image: "postgres:15.3"
    restart: "always"
    environment:
      POSTGRES_USER: "tinytinyrss"
      POSTGRES_PASSWORD: "HPALUhAY28G4LWDf"
      POSTGRES_DB: "tinytinyrss"
    volumes:
      - "./ttrss/data/pgdata:/var/lib/postgresql/data"
    logging:
      driver: "journald"
    stop_grace_period: 30s
    shm_size: "512M"
    networks:
      - schwifty

  ttrss:
    container_name: "ttrss"
    image: "heapy/ttrss:main"
    restart: "always"
    environment:
      - TTRSS_HTTP_PROXY=${TTRSS_HTTP_PROXY
    volumes:
      - "./ttrss/data/cache:/ttrss/reader/cache"
      - "./ttrss/data/lock:/ttrss/reader/lock"
      - "./ttrss/data/feed-icons:/ttrss/reader/feed-icons"
    logging:
      driver: "journald"
    stop_grace_period: 30s
    depends_on:
      - ttrss_database
    networks:
      - schwifty

  ttrss_nginx:
    container_name: "ibragimov.by-reader"
    image: "heapy/ttrss-nginx:main"
    command: [ "nginx-debug", "-g", "daemon off;" ]
    restart: "always"
    volumes:
      - "./ttrss/data/cache:/ttrss/reader/cache"
      - "./ttrss/data/lock:/ttrss/reader/lock"
      - "./ttrss/data/feed-icons:/ttrss/reader/feed-icons"
    logging:
      driver: "journald"
    stop_grace_period: 30s
    networks:
      - schwifty
    depends_on:
      - ttrss

  kotlin_link:
    container_name: "kotlin.link"
    image: "ghcr.io/kotlinby/awesome-kotlin:main"
    restart: "always"
    logging:
      driver: "journald"
    stop_grace_period: 30s
    networks:
      - schwifty
