networks:
  schwifty:
    name: schwifty
    driver: bridge

services:
  cloudflared:
    container_name: "cloudflared"
    image: "cloudflare/cloudflared:latest"
    command: [ "tunnel", "--no-autoupdate", "run"]
    restart: always
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    logging:
      driver: "journald"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "256M"
    networks:
      - schwifty
    depends_on:
#      - ibragimov_by_currency
#      - ruslan_ibragimov_by
      - heapy_io_kotlin_jobs
#      - heapy_io
  
#  ibragimov_by_currency:
#    container_name: "ibragimov.by-currency"
#    image: "ghcr.io/irus/currency:main"
#    restart: "always"
#    logging:
#      driver: "journald"
#    deploy:
#      resources:
#        limits:
#          cpus: "1"
#          memory: "32M"
#    stop_grace_period: 30s
#    mem_swappiness: 0
#    networks:
#      - schwifty
#
#  ruslan_ibragimov_by:
#    container_name: "ruslan.ibragimov.by"
#    image: "ghcr.io/irus/blog:main"
#    restart: "always"
#    logging:
#      driver: "journald"
#    deploy:
#      resources:
#        limits:
#          cpus: "1"
#          memory: "32M"
#    stop_grace_period: 30s
#    mem_swappiness: 0
#    networks:
#      - schwifty

  heapy_io_kotlin_jobs:
    container_name: "heapy.io-kotlin_jobs"
    image: "ghcr.io/heapy/kotlin_jobs:main"
    restart: "always"
    logging:
      driver: "journald"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "32M"
    stop_grace_period: 30s
    mem_swappiness: 0
    networks:
      - schwifty
#
#  heapy_io:
#    container_name: "heapy.io"
#    image: "ghcr.io/heapy/heapy.io:main"
#    restart: "always"
#    logging:
#      driver: "journald"
#    deploy:
#      resources:
#        limits:
#          cpus: "1"
#          memory: "32M"
#    stop_grace_period: 30s
#    mem_swappiness: 0
#    networks:
#      - schwifty
