#!/bin/bash

# Install script
# source /home/pi/heapy-configuration/schwifty-server/functions

PROJECT="/home/pi/heapy-configuration/schwifty-server";

function hh_system_update() {
  echo "[📦] Update packages"
  apt update
  apt dist-upgrade -y
  apt autoremove -y
  apt autoclean
}

function hh_pull_docker_images() {
  echo "[🆕] Pull latest images"
  docker pull ghcr.io/irus/blog:main
  docker pull ghcr.io/irus/currency:main
  docker pull ghcr.io/heapy/heapy.io:main
  docker pull ghcr.io/heapy/kotlin_jobs:main
  docker pull ghcr.io/kotlinby/awesome-kotlin:main
}

function hh_build_ttrss() {
    echo "[🔨] Build new ttrss images"
    cd "${PROJECT}/ttrss/docker" || exit 1
    ./build.sh
}

function hh_compose_up() {
  echo "[🌈] Update containers"
  cd "${PROJECT}" || exit 1
  docker compose up -d
}

function hh_prune_docker_images() {
  echo "[🧹] Remove unused images";
  docker system prune -f;
}

function hh_update() {
  hh_system_update;
  hh_pull_docker_images;
  hh_build_ttrss;
  hh_compose_up;
  hh_prune_docker_images;
}

function home() {
  cd $PROJECT || exit 1
}

function hh_update_feed() {
    /usr/bin/docker exec --user=1:1 ttrss /ttrss/reader/update.php --feeds --quite
}

alias ll='ls -alhF'

case "$1" in
  hh_update_docker)
    hh_pull_docker_images;
    hh_compose_up;
    ;;
  hh_update_feed)
    hh_update_feed;
    ;;
  *)
    ;;
esac
