services:
  mosquitto:
    container_name: "mosquitto"
    restart: "always"
    image: "eclipse-mosquitto:2.0"
    volumes:
      - "./mosquitto/config:/mosquitto/config"
      - "./mosquitto/data:/mosquitto/data"
      - "./mosquitto/log:/mosquitto/log"
    ports:
      - "127.0.0.1:1883:1883"
      - "127.0.0.1:9001:9001"
  zigbee2mqtt:
    container_name: "zigbee2mqtt"
    restart: "always"
    privileged: true
    image: "koenkk/zigbee2mqtt:1.35.1"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - "./zigbee2mqtt:/app/data"
      - "/run/udev:/run/udev:ro"
    ports:
      - "0.0.0.0:9002:9002"
    environment:
      - "TZ=Europe/Minsk"
  home_assistant:
    container_name: "home_assistant"
    restart: "always"
    privileged: true
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - "./home_assistant:/config"
      - "/etc/localtime:/etc/localtime:ro"
    network_mode: "host"
  frigate:
    container_name: "frigate"
    restart: "unless-stopped"
    privileged: true
    image: "ghcr.io/blakeblackshear/frigate:stable"
    shm_size: "64mb"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./frigate/config:/config"
      - "./frigate/storage:/media/frigate"
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    environment:
      FRIGATE_RTSP_PASSWORD: "${FRIGATE_RTSP_PASSWORD}"
