x-journald: &journald
  logging:
    driver: "journald"

services:
  mosquitto:
    <<: *journald
    container_name: "mosquitto"
    restart: "always"
    image: "eclipse-mosquitto:2.1-alpine"
    volumes:
      - "./mosquitto/config:/mosquitto/config"
      - "./mosquitto/data:/mosquitto/data"
      - "./mosquitto/log:/mosquitto/log"
    ports:
      - "0.0.0.0:1883:1883"
      - "0.0.0.0:9001:9001"
  zigbee2mqtt:
    <<: *journald
    container_name: "zigbee2mqtt"
    restart: "always"
    privileged: true
    image: "koenkk/zigbee2mqtt:2.12.1"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - "./zigbee2mqtt:/app/data"
      - "/run/udev:/run/udev:ro"
    ports:
      - "0.0.0.0:9002:9002"
    environment:
      - "TZ=Europe/Minsk"
  prometheus:
    <<: *journald
    container_name: "prometheus"
    restart: "always"
    image: "prom/prometheus:v3.13.1"
    user: "1000:1000"
    volumes:
      - "./prometheus/data:/prometheus"
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
    network_mode: "host"
  home_assistant:
    <<: *journald
    container_name: "home_assistant"
    restart: "always"
    privileged: true
    image: "ghcr.io/home-assistant/home-assistant:2026.7"
    volumes:
      - "./home_assistant:/config"
      - "/etc/localtime:/etc/localtime:ro"
      - "/run/dbus:/run/dbus:ro"
    network_mode: "host"
  matter-server:
    <<: *journald
    container_name: "matter-server"
    restart: "always"
    image: "ghcr.io/matter-js/matterjs-server:stable"
    volumes:
      - "./matter-server:/data"
      - "/run/dbus:/run/dbus:ro"
    network_mode: "host"
    environment:
      - "PRIMARY_INTERFACE=eth0"
