version: "3.9"

networks:
  gotron:
    name: gotron
    driver: bridge

services:
  ingress:
    image: "nginx:stable-alpine"
    container_name: "ingress"
    restart: "always"
    user: "${HOST_USER}"
    volumes:
      - ${DATA_HOME}/config/nginx/conf.d:/etc/nginx/conf.d
      - ${DATA_HOME}/data/letsencrypt:/letsencrypt
      - ${DATA_HOME}/data/nginx/logs:/logs
      - ${DATA_HOME}/data/nginx/config:/config
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "64M"
    stop_grace_period: 30s
    sysctls:
      net.core.somaxconn: 2048
    ulimits:
      nofile:
        soft: 10240
        hard: 40960
    networks:
      - gotron
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  supolka_com:
    container_name: "supolka_com"
    image: "ghcr.io/irus/open_pirs:main"
    restart: "always"
    logging:
      driver: "journald"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "16M"
    networks:
      - gotron

  kotlin_link:
    container_name: "kotlin_link"
    image: "ghcr.io/kotlinby/awesome-kotlin:main"
    restart: "always"
    logging:
      driver: "journald"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "32M"
    networks:
      - gotron

  repo_kotlin_link:
    image: "ghcr.io/heapy/repo.kotlin.link:${REPO_KOTLIN_LINK_RELEASE}"
    container_name: "repo.kotlin.link"
    restart: "always"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/healthcheck" ]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "journald"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512M"
    networks:
      - gotron

  kotbot:
    image: "ghcr.io/heapy/kotbot:${KOTBOT_VERSION}"
    container_name: "kotbot"
    restart: "always"
    user: "${HOST_USER}"
    environment:
      KOTBOT_OPTS: "-Xmx128m"
      KOTBOT_TOKEN: "${KOTBOT_TOKEN}"
      KOTBOT_VERSION: "${KOTBOT_VERSION}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "journald"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "256M"
    networks:
      - gotron

  ttrss_database:
    container_name: "ttrss_database"
    image: "postgres:14.3"
    restart: "always"
    environment:
      POSTGRES_USER: "tinytinyrss"
      POSTGRES_PASSWORD: "HPALUhAY28G4LWDf"
      POSTGRES_DB: "tinytinyrss"
    volumes:
      - "${DATA_HOME}/data/ttrss/pgdata:/var/lib/postgresql/data"
    logging:
      driver: "journald"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024M"
    networks:
      - gotron

  ttrss:
    container_name: "ttrss"
    image: "heapy/ttrss:latest"
    restart: "always"
    volumes:
      - "${DATA_HOME}/data/ttrss/data/cache:/ttrss/reader/cache"
      - "${DATA_HOME}/data/ttrss/data/lock:/ttrss/reader/lock"
      - "${DATA_HOME}/data/ttrss/data/feed-icons:/ttrss/reader/feed-icons"
    logging:
      driver: "journald"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "256M"
    depends_on:
      - ttrss_database
    networks:
      - gotron

  ttrss_nginx:
    container_name: "ttrss_nginx"
    image: "heapy/ttrss-nginx:latest"
    command: [ "nginx-debug", "-g", "daemon off;" ]
    restart: "always"
    volumes:
      - "${DATA_HOME}/data/ttrss/data/cache:/ttrss/reader/cache"
      - "${DATA_HOME}/data/ttrss/data/lock:/ttrss/reader/lock"
      - "${DATA_HOME}/data/ttrss/data/feed-icons:/ttrss/reader/feed-icons"
    logging:
      driver: "journald"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "32M"
    networks:
      - gotron
    depends_on:
      - ttrss

  ibragimov_by_currency:
    container_name: "ibragimov_by_currency"
    image: "ghcr.io/irus/currency:main"
    restart: "always"
    logging:
      driver: "journald"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "16M"
    networks:
      - gotron

  ruslan_ibragimov_by:
    container_name: "ruslan_ibragimov_by"
    image: "ghcr.io/irus/blog:main"
    restart: "always"
    logging:
      driver: "journald"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "32M"
    networks:
      - gotron

  heapy_io_kotlin_jobs:
    container_name: "heapy_io_kotlin_jobs"
    image: "ghcr.io/heapy/kotlin_jobs:main"
    restart: "always"
    logging:
      driver: "journald"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "16M"
    networks:
      - gotron

  heapy_io:
    container_name: "heapy_io"
    image: "ghcr.io/heapy/heapy.io:main"
    restart: "always"
    logging:
      driver: "journald"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "16M"
    networks:
      - gotron

  wireguard:
    container_name: "wireguard"
    image: "weejewel/wg-easy"
    restart: "always"
    environment:
      WG_HOST: "vpn.heapy.io"
      PASSWORD: "${WIREGUARD_PASSWORD}"
    volumes:
      - "${DATA_HOME}/data/wireguard:/etc/wireguard"
    logging:
      driver: "journald"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "256M"
    ports:
      - "51820:51820/udp"
    cap_add:
      - "NET_ADMIN"
      - "SYS_MODULE"
    sysctls:
      - "net.ipv4.conf.all.src_valid_mark=1"
      - "net.ipv4.ip_forward=1"
    networks:
      - gotron

  mtproto:
    container_name: "mtproto"
    image: "heapy/mtproto:latest"
    restart: "always"
    environment:
      PROXY_SECRET: "${PROXY_SECRET}"
    logging:
      driver: "journald"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "256M"
    ports:
      - "8888:8888"

  grafana:
    image: "grafana/grafana:8.5.3"
    container_name: "grafana"
    restart: "always"
    user: "${HOST_USER}"
    volumes:
      - "${DATA_HOME}/data/grafana:/var/lib/grafana"
    logging:
      driver: "journald"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "256M"
    ports:
      - "3000:3000"

  prometheus:
    image: "prom/prometheus:v2.35.0"
    container_name: "prometheus"
    restart: "always"
    user: "${HOST_USER}"
    volumes:
      - "${DATA_HOME}/data/prometheus:/prometheus"
      - "${DATA_HOME}/config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
    logging:
      driver: "journald"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "256M"
