networks:
  gotron:
    name: gotron
    driver: bridge

services:
  ingress:
    image: "nginx:stable-alpine"
    container_name: "ingress"
    restart: "always"
    logging:
      driver: "journald"
    volumes:
      - ./ingress/nginx/conf.d:/etc/nginx/conf.d
      - ./ingress/data/letsencrypt:/letsencrypt
      - ./ingress/data/nginx/logs:/logs
      - ./ingress/data/nginx/config:/config
    stop_grace_period: 30s
    sysctls:
      net.core.somaxconn: 2048
    ulimits:
      nofile:
        soft: 10240
        hard: 40960
    networks:
      - gotron
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    depends_on:
      - wireguard

  wireguard:
    container_name: "wireguard"
    image: "weejewel/wg-easy"
    restart: "always"
    environment:
      WG_HOST: "vpn.heapy.io"
      PASSWORD: "${WIREGUARD_PASSWORD}"
    volumes:
      - "./wireguard/data/:/etc/wireguard"
    logging:
      driver: "journald"
    stop_grace_period: 30s
    ports:
      - "51820:51820/udp"
    cap_add:
      - "NET_ADMIN"
      - "SYS_MODULE"
    sysctls:
      - "net.ipv4.conf.all.src_valid_mark=1"
      - "net.ipv4.ip_forward=1"
    networks:
      - gotron

  mtproto:
    container_name: "mtproto"
    image: "heapy/mtproto:main"
    restart: "always"
    environment:
      PROXY_SECRET: "${PROXY_SECRET}"
    logging:
      driver: "journald"
    stop_grace_period: 30s
    ports:
      - "8888:8888"
    networks:
      - gotron
