services:
  wireguard:
    container_name: "wireguard"
    image: "ghcr.io/wg-easy/wg-easy:latest"
    restart: "always"
    environment:
      WG_HOST: "vpn.heapy.io"
      PASSWORD: "${WIREGUARD_PASSWORD}"
    volumes:
      - "./wireguard/data/:/etc/wireguard"
    logging:
      driver: "journald"
    stop_grace_period: 30s
    ports:
      - "51820:51820/udp"
      # http://vpn.heapy.io:51821/
      # - "51821:51821/tcp"
    cap_add:
      - "NET_ADMIN"
      - "SYS_MODULE"
    sysctls:
      - "net.ipv4.conf.all.src_valid_mark=1"
      - "net.ipv4.ip_forward=1"
