#!/bin/bash

# Install script
# source /mnt/volume_ams3_01/heapy-configuration/poopybutthole/functions

PROJECT="/mnt/volume_ams3_01/heapy-configuration/poopybutthole";

function hh_update_system() {
  echo "[📦] Update packages"
  dnf update -y
}

# Generated
#  proxy.ibragimov.by
#  bkug.by
#  store.bkug.by
#  kotbot.heapy.io
#  vpn.heapy.io
#  kotlin.link
#  repo.kotlin.link
#  shop.streetball.name
#  streetball.by
#  streetball.name
function hh_update_certificates() {
  echo "[📃] Update certificates"
  mkdir -p "${PROJECT}/ingress/data/letsencrypt/etc"
  mkdir -p "${PROJECT}/ingress/data/letsencrypt/var"

  docker stop ingress

  docker run -it --rm --name certbot \
    -v "${PROJECT}/ingress/data/letsencrypt/etc:/etc/letsencrypt" \
    -v "${PROJECT}/ingress/data/letsencrypt/var:/var/lib/letsencrypt" \
    -p 80:80 \
    -p 443:443 \
    certbot/certbot renew

  docker start ingress
}

function hh_update() {
  hh_update_system;
  hh_update_certificates;
}

function home() {
  cd $PROJECT || exit 1
}

function hh_issue_certificate() {
  DOMAIN=$1

  docker stop ingress

  docker run -it --rm --name certbot \
    -v "${PROJECT}/ingress/data/letsencrypt/etc:/etc/letsencrypt" \
    -v "${PROJECT}/ingress/data/letsencrypt/var:/var/lib/letsencrypt" \
    -p 80:80 \
    -p 443:443 \
    certbot/certbot certonly --standalone -d "${DOMAIN}"

  docker start ingress
}

function hh_delete_certificate() {
  docker stop ingress

  docker run -it --rm --name certbot \
    -v "${PROJECT}/ingress/data/letsencrypt/etc:/etc/letsencrypt" \
    -v "${PROJECT}/ingress/data/letsencrypt/var:/var/lib/letsencrypt" \
    -p 80:80 \
    -p 443:443 \
    certbot/certbot delete

  docker start ingress
}

