#!/bin/bash

# Install script
# source /root/heapy-configuration/poopybutthole/functions

PROJECT="/root/heapy-configuration/poopybutthole";

function hh_update_system() {
  echo "[📦] Update packages"
  sudo apt update
  sudo apt list --upgradable
  sudo apt dist-upgrade -y
  sudo apt autoremove -y
  sudo apt autoclean
  sudo apt clean
}

function hh_update() {
  hh_update_system;
}

function hh_pull_docker_images() {
  echo "[🆕] Pull latest images"
  docker pull ghcr.io/wg-easy/wg-easy:latest
}

function home() {
  cd "${PROJECT}" || exit 1
}

function hh_compose_up() {
  echo "[🌈] Update containers"
  cd "${PROJECT}" || exit 1
  docker compose up -d
}
