version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.3.0
    restart: always
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.3.0
    restart: always
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "0.0.0.0:3101:3000"
    networks:
      - loki
