# https://prometheus.io/docs/prometheus/latest/configuration/configuration/

global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "kotbot"
    metrics_path: "/metrics"
    scrape_interval: 30s
    static_configs:
      - targets: ["kotbot:8080"]

  - job_name: "repo_kotlin_link"
    metrics_path: "/metrics"
    scrape_interval: 30s
    static_configs:
      - targets: ["repo_kotlin_link:8080"]

  - job_name: "kotlin_link"
    metrics_path: "/metrics"
    scrape_interval: 30s
    static_configs:
      - targets: ["kotlin_link:8080"]
