name: "Build"
on:
  push:
    branches:
      - "main"
    paths:
      - "updater/**"
jobs:
  build:
    name: "Build updater"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "zulu"
      - run: ./gradlew check distTar
        working-directory: updater
      - uses: actions/upload-artifact@v2
        with:
          name: "Kotlin Application"
          path: "updater/build/distributions/updater.tar"
          retention-days: 1
  build-and-push-image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: "Kotlin Application"
          path: "updater/build/distributions/"
      - name: "Untar files"
        working-directory: updater
        run: mkdir -p build/install && tar -xvf build/distributions/updater.tar -C $_
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1
      - name: "Login to GHCR"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password:  ${{ secrets.GITHUB_TOKEN }}
      - name: "Build and push"
        uses: docker/build-push-action@v2
        with:
          context: updater
          push: true
          tags: |
            ghcr.io/irus/updater:main
            ghcr.io/irus/updater:b${{ github.run_number }}
